### ISSUE TITLE
Use `Winget` instead of Chocolatey

### ISSUE THREAD

**Issue by Bigous** [LeDragoX/Win-10-Smart-Debloat-Tools#16]
### Description

Sinse win10, winget is the official package manager for installing and controlling installed apps in windows.
It has became much more complete and mature sinse win11.
Why not have the option to have it as the background installer instead of chocolatey?

### Reason

We already have winget installed and running on win11 by default, don't need to install another package manager.

### Examples

N/A

**Comment by LeDragoX** [comment]
Okay, here goes the reason behind still having `Chocolatey`, some apps (e.g. WinRaR) install a **localized** version, which helps the user utilizing the program in it's native language without requiring to change the command to install. For example, the context menu to compact/extract files came in brazilian for me the 1st time, but not in `Winget`, but i'll check again

I know we can use `Get-Culture` to find your current language, but i didn't tested with `Winget` yet. When i got the time i'll test and update the script to not use `Chocolatey` anymore, leaving traces, because it still can be useful for some users that already installed Chocolatey.

And another plus, `Chocolatey` still have packages that `Winget` won't, as it's maintained by the community for a long time.

**Comment by LeDragoX** [comment]
Another case that highlights **Chocolatey** is in this case which happens a lot,
**Choco** package versions being newer than **Winget**
![image](https://user-images.githubusercontent.com/27643047/160620623-24cfe5fc-2ce5-48aa-976d-1de75900e773.png)

**Comment by ItzLevvie** [comment]
> Choco package versions being newer than Winget

This is because the Rufus package in the WinGet repository is an MSIX package and the Rufus developer no longer publishes MSIX builds to GitHub Releases so it's one of the reasons why it hasn't been updated. We've not removed that because portable apps are in development for future releases of WinGet.

Microsoft Store now allows you to submit Win32 apps; it's one of the places where people should install their apps as long the publisher has already submitted an application there.

For Rufus in WinGet, newer releases are now part of `9PC3H3V7Q9CH` where the publishing deployment is much faster than Chocolately as the releases are published by the publisher as soon as a new build goes out.

WinGet is still sort of far from feature parity with Chocolately, though, portable apps and zip files are still being worked on for a future WinGet release.

**Comment by LeDragoX** [comment]
> For Rufus in WinGet, newer releases are now part of `9PC3H3V7Q9CH` where the publishing deployment is much faster than Chocolately as the releases are published by the publisher as soon as a new build goes out.

Thanks, i'll put this version instead. ;)

**Comment by LeDragoX** [comment]
The remaining packages that still on Chocolatey, because Winget doesn't have it:

- `ublockorigin-chrome` (i'll remove when there's no need anymore to use chocolatey, i like this advertising blocker, but for a "native" experience it's fine to remove)
- `paint.net` (show from msstore, but its paid)
- `adb`
- `scrcpy`
- `Ventoy`

**Comment by LeDragoX** [comment]
I was testing the version of `Rufus` from chocolatey vs msstore via winget
What i can tell is that the MS Store version didn't received the TPM 2.0 bypass yet.

> But maybe within time, they'll match the same features.

<details>

**MS Store**
![image](https://user-images.githubusercontent.com/27643047/162619567-3563f0bf-8887-4a4c-981d-684f32f5aa20.png)

**Chocolatey**
![image](https://user-images.githubusercontent.com/27643047/162619527-82f57cdb-a17e-46af-87f5-843f65faa383.png)

</details>

**Comment by Bigous** [comment]
Just passing to thank you for the effort, man!

**Comment by LeDragoX** [comment]
At least i can talk a good news about a recent change i've made with Chocolatey.
It'll not try to install the dependencies linked with the software you're installing anymore.
Just the one package needed and done, meaning less bloat on your installed packages:
`choco list --local`

If someone wants to uninstall the bloat, uninstall the package with this command:
`choco uninstall (a package from the list) --remove-dependencies -y`
Then reinstall again with the GUI.

**Comment by LeDragoX** [comment]
To end this Issue, i need to apologize, Chocolatey is still needed to this project, maybe in future `winget` receive more packages safely, making chocolatey unnecessary.

Thanks for your contributions! ❤️
