### ISSUE TITLE
Rename Streamlabs OBS to `Streamlabs`

### ISSUE THREAD

**Issue by Mormamu** [LeDragoX/Win-10-Smart-Debloat-Tools#17]
### Description

Rename Streamlabs OBS to just Streamlabs.

### Reason

There is a very clear difference between streamlabs and OBS plus slobs recently rebranded their software to just streamlabs.

Renaming slobs to streamlabs would help with diferentiating between the 2 programs.

Personally I would like to see slobs removed entirely since its just obs but in electron.

**Comment by LeDragoX** [comment]
Currently there are 2 different versions from Streamlabs Products.

![image](https://user-images.githubusercontent.com/27643047/168153368-644b2e39-1538-4166-90d0-5e3a4bbcce9d.png)

I'm checking which version matches the <https://streamlabs.com/> version.

Apparently, the Streamlabs Desktop and the Streamlabs OBS are the same.

Sorry i didn't saw this before, every time some one installed the Streamlabs OBS offered in the Script, it went to download (again) the newest version like this:
![image](https://user-images.githubusercontent.com/27643047/168154718-edaea079-1eda-4078-bfae-da832b3d8e4b.png)

> Renaming slobs to streamlabs would help with diferentiating between the 2 programs.

- To finish this issue, after comitting and pushing it, `Streamlabs OBS` will be renamed as `Streamlabs`.
- And the version which will be installed will be `Streamlabs.Streamlabs` (Streamlabs Desktop)

> Personally I would like to see slobs removed entirely since its just obs but in electron.

Me either, because it provides a minimal installation with pure OBS, **but**, this modified OBS helps people who work on Streamlabs ecossystem, that's the reason i've kept it.

**Comment by LeDragoX** [comment]
I've been thinking of adding the _Elgato Stream Deck_ app too, a lot of streamers use it.

![image](https://user-images.githubusercontent.com/27643047/168157458-900e4a57-fc9d-4d81-8954-0b31e53c7e66.png)

Pushing to `main` right after this issue is solved.
