### ISSUE TITLE
LibreOffice package not found

### ISSUE THREAD

**Issue by Lis0v** [LeDragoX/Win-10-Smart-Debloat-Tools#38]
### Describe the Bug

LibreOffice package not found.

### How can this issue be reproduced?

1. Open GUI script
2. Go to Software Install Tab
3. Check LibreOffice box
4. Click Install Selected

### Expected behavior?

Install LibreOffice to local machine

### Operating System

Windows 11 (64-bits)

### Operating System Version

21H2

### Date Executed

2022-06-27

### Screenshots

![image](https://user-images.githubusercontent.com/61664701/175954024-52631f1b-07c1-4a7a-b9b1-a8afb0d4fe16.png)

**Comment by LeDragoX** [comment]
Thanks for reporting this, it seems they changed the package property to **TheDocumentFoundation.LibreOffice**
![image](https://user-images.githubusercontent.com/27643047/175960181-b09dd6c8-c0c8-4ecb-8c11-948c1fff4f71.png)

Working and testing on the change RN.

**Comment by LeDragoX** [comment]
Downloading through `winget` is so slow, because it's getting the newer version by the old versions repository.
![image](https://user-images.githubusercontent.com/27643047/175963214-b6afa44b-ccb6-49de-b72e-b18aab25d1da.png)

Chocolatey is doing the same thing, this is going to take an **Eternity**!
![image](https://user-images.githubusercontent.com/27643047/175963873-0213e79d-0cd2-4c7c-8e77-564845af8f67.png)

I think this time is better to get the installer via website...sad
